UPDATE destinations SET name = 'Huế', province = 'Thừa Thiên Huế' WHERE slug = 'hue';
UPDATE destinations SET name = 'Đà Nẵng', province = 'Đà Nẵng' WHERE slug = 'da-nang';
UPDATE destinations SET name = 'Quy Nhơn', province = 'Bình Định' WHERE slug = 'quy-nhon';
UPDATE destinations SET name = 'Phong Nha', province = 'Quảng Bình' WHERE slug = 'phong-nha';
UPDATE destinations SET name = 'Hà Nội', province = 'Hà Nội' WHERE slug = 'ha-noi';
UPDATE destinations SET name = 'Sapa', province = 'Lào Cai' WHERE slug = 'sapa';
UPDATE destinations SET name = 'Ninh Bình', province = 'Ninh Bình' WHERE slug = 'ninh-binh';
UPDATE destinations SET name = 'Mù Cang Chải', province = 'Yên Bái' WHERE slug = 'mu-cang-chai';
UPDATE destinations SET name = 'Phú Quốc', province = 'Kiên Giang' WHERE slug = 'phu-quoc';
UPDATE destinations SET name = 'Côn Đảo', province = 'Bà Rịa - Vũng Tàu' WHERE slug = 'con-dao';
UPDATE destinations SET name = 'Vũng Tàu', province = 'Bà Rịa - Vũng Tàu' WHERE slug = 'vung-tau';
UPDATE destinations SET name = 'Mũi Né', province = 'Bình Thuận' WHERE slug = 'mui-ne';
UPDATE destinations SET name = 'Cần Thơ', province = 'Cần Thơ' WHERE slug = 'can-tho';
UPDATE destinations SET name = 'Châu Đốc', province = 'An Giang' WHERE slug = 'chau-doc';
UPDATE destinations SET name = 'Mỹ Tho', province = 'Tiền Giang' WHERE slug = 'my-tho';
UPDATE destinations SET name = 'Hà Tiên', province = 'Kiên Giang' WHERE slug = 'ha-tien';
UPDATE destinations SET name = 'Bến Tre', province = 'Bến Tre' WHERE slug = 'ben-tre';

UPDATE transport_hubs SET name = 'Sân bay Tân Sơn Nhất' WHERE code = 'tan_son_nhat_airport';
UPDATE transport_hubs SET name = 'Sân bay Nội Bài' WHERE code = 'noi_bai_airport';
UPDATE transport_hubs SET name = 'Sân bay Đà Nẵng' WHERE code = 'da_nang_airport';
UPDATE transport_hubs SET name = 'Sân bay Thọ Xuân' WHERE code = 'tho_xuan_airport';
UPDATE transport_hubs SET name = 'Sân bay Cam Ranh' WHERE code = 'cam_ranh_airport';
UPDATE transport_hubs SET name = 'Sân bay Phú Quốc' WHERE code = 'phu_quoc_airport';
UPDATE transport_hubs SET name = 'Sân bay Cần Thơ' WHERE code = 'can_tho_airport';
UPDATE transport_hubs SET name = 'Sân bay Liên Khương' WHERE code = 'lien_khuong_airport';
UPDATE transport_hubs SET name = 'Sân bay Phù Cát' WHERE code = 'phu_cat_airport';
UPDATE transport_hubs SET name = 'Sân bay Vinh' WHERE code = 'vinh_airport';
UPDATE transport_hubs SET name = 'Sân bay Cát Bi' WHERE code = 'cat_bi_airport';
UPDATE transport_hubs SET name = 'Sân bay Phú Bài' WHERE code = 'phu_bai_airport';
UPDATE transport_hubs SET name = 'Sân bay Buôn Ma Thuột' WHERE code = 'buon_ma_thuot_airport';
UPDATE transport_hubs SET name = 'Sân bay Pleiku' WHERE code = 'pleiku_airport';
UPDATE transport_hubs SET name = 'Sân bay Tuy Hòa' WHERE code = 'tuy_hoa_airport';
UPDATE transport_hubs SET name = 'Sân bay Chu Lai' WHERE code = 'chu_lai_airport';
UPDATE transport_hubs SET name = 'Sân bay Đồng Hới' WHERE code = 'dong_hoi_airport';
UPDATE transport_hubs SET name = 'Sân bay Rạch Giá' WHERE code = 'rach_gia_airport';
UPDATE transport_hubs SET name = 'Sân bay Cà Mau' WHERE code = 'ca_mau_airport';
UPDATE transport_hubs SET name = 'Sân bay Côn Đảo' WHERE code = 'con_dao_airport';
UPDATE transport_hubs SET name = 'Sân bay Điện Biên' WHERE code = 'dien_bien_airport';
UPDATE transport_hubs SET name = 'Ga Hà Nội' WHERE code = 'ha_noi_station';
UPDATE transport_hubs SET name = 'Ga Vinh' WHERE code = 'vinh_station';
UPDATE transport_hubs SET name = 'Ga Huế' WHERE code = 'hue_station';
UPDATE transport_hubs SET name = 'Ga Đà Nẵng' WHERE code = 'da_nang_station';
UPDATE transport_hubs SET name = 'Ga Nha Trang' WHERE code = 'nha_trang_station';
UPDATE transport_hubs SET name = 'Ga Quy Nhơn' WHERE code = 'quy_nhon_station';
UPDATE transport_hubs SET name = 'Ga Sài Gòn' WHERE code = 'sai_gon_station';
UPDATE transport_hubs SET name = 'Cảng Hà Tiên' WHERE code = 'ha_tien_port';
UPDATE transport_hubs SET name = 'Cảng Phú Quốc' WHERE code = 'phu_quoc_port';
UPDATE transport_hubs SET name = 'Cảng Trần Đề' WHERE code = 'tran_de_port';
UPDATE transport_hubs SET name = 'Cảng Côn Đảo' WHERE code = 'con_dao_port';
