// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRaECv2D-RqNmhqKzIBOZs_vezjO1P9Eg',
    appId: '1:518596179238:web:938728619d9853bbf93de7',
    messagingSenderId: '518596179238',
    projectId: 'travelbytemp',
    authDomain: 'travelbytemp.firebaseapp.com',
    storageBucket: 'travelbytemp.firebasestorage.app',
    measurementId: 'G-5RPPPFXE40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivTbvgwDJK7R4iN0WoqhuhOGE_ofQtKQ',
    appId: '1:518596179238:android:258abd07e7209ee3f93de7',
    messagingSenderId: '518596179238',
    projectId: 'travelbytemp',
    storageBucket: 'travelbytemp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbti6z2T_1QprzEJKZb78-riiuR6g4nUI',
    appId: '1:518596179238:ios:b1cb9ca09ac1996bf93de7',
    messagingSenderId: '518596179238',
    projectId: 'travelbytemp',
    storageBucket: 'travelbytemp.firebasestorage.app',
    iosClientId: '518596179238-9tod3h4gvk9j8m2jdoduocoq4q53lqrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
